### PR TITLE
site-packages location should not be hard coded

### PR DESCRIPTION
**Pull request by cddigi**
using black for formatting and isort for import sorting

### CODE REVIEW

**Comment by BBC-Esq** [comment]
This seems interesting...I had one other user report something similar...Is there a way to view your entire script without red and green showing the removed and added portions by chance?

**Comment by cddigi** [comment]
> This seems interesting...I had one other user report something similar...Is there a way to view your entire script without red and green showing the removed and added portions by chance?

image

**Comment by BBC-Esq** [comment]
Thanks, I'll review and test ASAP.  Another user mentioned this possible error as well.  I added instructions both on the github readme as well as on the release page.  Can you explain where the correct folder structure was on your system, and which system you're using such as MacOS or Linux or what not?

**Comment by cddigi** [comment]
MacOS

Screenshot 2023-12-27 at 3 12 48 PM

**Comment by BBC-Esq** [comment]
I tried pip install site but it didn't have a version that worked or so it said...do you have a link to the pypi by chance?

**Comment by BBC-Esq** [comment]
In a panic, I updated the scripts and made a 3.0.1 release, but did give credit for the solution...

**Pull request closed without merging**
